sudo: false
language: node_js
node_js: "stable"
branches:
  only:
  - gh-pages
after_success:
- git config --global user.name 'azu'
- git config --global user.email 'azuciao@gmail.com'
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "gh-pages" && ./tools/update-source-data.sh
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "gh-pages" && ./tools/update-realtime.sh
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "gh-pages" && ./tools/update-next-draft.sh
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "gh-pages" && npm run twitter
